export const GIFTBOX_URL_EXPIRED = 'GIFTBOX_URL_EXPIRED'
export const GIFTBOX_NOT_FOUND = 'GIFTBOX_NOT_FOUND'
export const GIFTBOX_ALREADY_OPENED = 'GIFTBOX_ALREADY_OPENED'
export type BoxStatus = 'closed' | 'opening' | 'opened' | 'fading'
export const NOTICE_NOT_FOUND = 'NOTICE_NOT_FOUND'
